### ISSUE TITLE
运行的时候Cannot find module '~taro-parse/dist/style/main'

### ISSUE THREAD

**Issue by jun12342012** [werfei/taro-parse#4]
请问
thirdScriptError
Cannot find module '~taro-parse/dist/style/main'
Error: Cannot find module '~taro-parse/dist/style/main'
    at webpackMissingModule (http://127.0.0.1:26860/appservice/__APP__/appservice.js:6895:65)
    at Object../node_modules/@tarojs/mini-runner/dist/loaders/wxTransformerLoader.js?!./src/pages/index/index.jsx?taro&type=script&parse=PAGE& (http://127.0.0.1:26860/appservice/__APP__/appservice.js:6895:167)
    at __webpack_require__ (http://127.0.0.1:26860/appservice/__APP__/appservice.js:81:30)
    at Module../src/pages/index/index.jsx?taro&type=script&parse=PAGE& (http://127.0.0.1:26860/appservice/__APP__/appservice.js:7022:173)
    at __webpack_require__ (http://127.0.0.1:26860/appservice/__APP__/appservice.js:81:30)
    at Module../src/pages/index/index.jsx (http://127.0.0.1:26860/appservice/__APP__/appservice.js:7005:97)
    at __webpack_require__ (http://127.0.0.1:26860/appservice/__APP__/appservice.js:81:30)
    at checkDeferredModules (http://127.0.0.1:26860/appservice/__APP__/appservice.js:47:23)
    at Array.webpackJsonpCallback [as push] (http://127.0.0.1:26860/appservice/__APP__/appservice.js:34:19)
    at http://127.0.0.1:26860/appservice/__APP__/appservice.js:6871:49``

**Comment by werfei** [comment]
请问您的引用方式是什么样呢？npm依赖正常吗？查看下node_modules下面的资源是否加载全了
![图片](https://user-images.githubusercontent.com/18606985/79298122-c20d1e80-7f12-11ea-8137-e523a4451b0c.png)

**Comment by jun12342012** [comment]
> 请问您的引用方式是什么样呢？npm依赖正常吗？查看下node_modules下面的资源是否加载全了
> ![图片](https://user-images.githubusercontent.com/18606985/79298122-c20d1e80-7f12-11ea-8137-e523a4451b0c.png)

修改好了
